use superherodb;
select name, heroID, costume from superhero;
select heroID, name, yearOgBirth from superhero order by yearOgBirth asc;
select heroID, costume from superhero order by name asc;
select heroID, name, yearOgBirth from superhero order by yearOgBirth desc;
select * from superhero where yearogBirth>=2000;
select * from superhero where yearogBirth<=1990;
select * from superhero where name='Rustman' or name='Lightning';
select * from superhero where name='Rustman' and costume='green';
select name, heroID, name, costume from superhero where costume='red';
select name, gear from superhero where name='SuperGenious';
select * from superhero where yearogBirth>=1930 and yearogBirth<=1990;
select * from superhero where yearogBirth between 1930 and 1990;
select name from superhero where name like '%er%';
select name from superhero where name like '%n';
select gear from superhero where gear like '_e%';
select yearogBirth from superhero where yearogBirth like '_9%';
select * from superhero where name like '%\%%';
select * from superhero where name not in ('Rustman','green');
select * from superhero where name in ('Rustman','green');
select * from superhero where name not in ('Rustman','green') and yearogBirth<2000;
update superhero set name ='super%Moron' where heroID=1;
select min(yearogBirth) as oldest, max(yearogBirth) as youngest from superhero;
select year(current_date)-max(yearogBirth) as age from superhero;
select year(current_date)-min(yearogBirth) as age from superhero;
select name from superhero where yearogBirth=(select min(yearogBirth) from superhero);
select name, year(current_date)-yearogBirth as age from superhero order by age desc;
select name, year(current_date)-yearogBirth as age from superhero;
insert into superhero values(8, 'Data_Master','Cape','red',1899);
insert into superhero values(9, 'DataxMaster','Capex','redx',1999);
select * from superhero where name like 'Data\_Master';
select * from superhero where name like 'Data_Master';
update superhero set name='Super_QL' where heroID=5;
select * from superhero where name like '%\_%';
update superhero set gear='JumpBoots', name='SuperMoron' where heroId=3;
update superhero set name='Super_QL' where heroID=5;
update superhero set gear='JumpBoots', name='SuperMoron' where heroId=3;
update superhero set gear='HelmeT', costume='blue' where heroID=4;
update superhero set gear='JumpBoots', yearogBirth=1930, name='SuperMoron' where heroID=6;
update superhero set yearogBirth=1960, costume='blue', name='Lightning' where heroID=2;
select * from superhero where heroId=2;
delete from superhero where heroId=5;
delete from superhero where heroID=2;
delete from superhero where yearogBirth=2017;
delete from superhero where gear='HelmeT' or name='SuperQL';
delete from superhero where name='super%Moron' or gear='Capex';
delete from superhero where name like 'Super%';
insert into superhero values(1, 'Rustman', 'Cape', 'blue', 1990);
select * from superhero where name='Rustman' and costume='green';
delete from superhero where name='Data_Master' or gear='Cape';
select * from superhero;
delete from superhero;
select * from superhero;
drop database superherodb;